CC=
 
all:
	gcc  *.c  -o  select -static -L/usr/lib  -I/mnt/hgfs/comgitlab/softwarekit/1app/select
	arm-linux-gnueabi-gcc  *.c  -o  selectarm -static -L/usr/lib  -I/mnt/hgfs/comgitlab/softwarekit/1app/select
 
 
clear:
	rm  *.o
